name: Release

on:
  workflow_dispatch:
    inputs:
      rname:
        description: "Release name"
        type: string
      tag_name:
        description: "Tag name"
        type: string

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Initialize repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Rust cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Build exe
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AppDataCleaner
          path: |
            target\release\AppDataCleaner.exe
            target\release\AppDataCleaner.pdb

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create archive
        run: cd artifacts/AppDataCleaner && zip -r "../../AppDataCleaner.zip" .

      - name: Move files
        run: |
          mv artifacts/AppDataCleaner/AppDataCleaner.exe AppDataCleaner.exe
          mv artifacts/AppDataCleaner/AppDataCleaner.pdb AppDataCleaner.pdb

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.rname }}
          tag_name: ${{ inputs.tag_name }}
          draft: false
          make_latest: true
          files: |
            AppDataCleaner.zip
            AppDataCleaner.exe
            AppDataCleaner.pdb
