name: Legacy code scan

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Check:
    name: Legacy code scan
    runs-on: ubuntu-latest
    #env:
    #  PATH: ${{ env.PATH }}:$(go env GOPATH)/bin
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install scanner
        run: |
          go install github.com/Done-0/fuck-u-code/cmd/fuck-u-code@latest

      - name: Run scan
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          fuck-u-code analyze --lang en_US --markdown > report.md

      - name: Print report
        run: |
          cat report.md

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.md
